runtime: java11
env: flex

automatic_scaling:
  target_cpu_utilization: 65
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180

resources:
  cpu: 1
  memory_gb: 3.5
  disk_size_gb: 10
